// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxdlqkWNzJ-rLZQfSUDlvIUn2M4OUpXqc',
    appId: '1:27243837152:android:02063c2c1c1a9859e28285',
    messagingSenderId: '27243837152',
    projectId: 'aumsatlogin',
    storageBucket: 'aumsatlogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6kkH3LERLBQ2UB487mnNnSsKMA_e-vc',
    appId: '1:27243837152:ios:6a0a3802ef01881fe28285',
    messagingSenderId: '27243837152',
    projectId: 'aumsatlogin',
    storageBucket: 'aumsatlogin.appspot.com',
    iosClientId: '27243837152-tfsklpksbsbe1l60j350umsb2ta6g7n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.aumsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6kkH3LERLBQ2UB487mnNnSsKMA_e-vc',
    appId: '1:27243837152:ios:6a0a3802ef01881fe28285',
    messagingSenderId: '27243837152',
    projectId: 'aumsatlogin',
    storageBucket: 'aumsatlogin.appspot.com',
    iosClientId: '27243837152-tfsklpksbsbe1l60j350umsb2ta6g7n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.aumsat',
  );
}
